// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/server/server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest 注册请求（携带完整机器信息）
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                          // Agent监听IP
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                     // Agent监听端口
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                    // 集群准入Token
	EnvInfo       *SystemEnvInfo         `protobuf:"bytes,4,opt,name=env_info,json=envInfo,proto3" json:"env_info,omitempty"` // 机器环境信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_server_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetEnvInfo() *SystemEnvInfo {
	if x != nil {
		return x.EnvInfo
	}
	return nil
}

// SystemEnvInfo 机器环境信息详情（与agent.proto中一致）
type SystemEnvInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                                 // 主机名
	Virtualization string                 `protobuf:"bytes,2,opt,name=virtualization,proto3" json:"virtualization,omitempty"`                     // 虚拟化类型
	UptimeSeconds  int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // 运行时间（秒）
	Os             *SystemInfo            `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                             // 操作系统信息
	Cpu            *CpuInfo               `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`                                           // CPU信息
	Memory         *MemoryInfo            `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`                                     // 内存信息
	Disks          []*DiskInfo            `protobuf:"bytes,7,rep,name=disks,proto3" json:"disks,omitempty"`                                       // 磁盘信息
	Networks       []*NetworkInfo         `protobuf:"bytes,8,rep,name=networks,proto3" json:"networks,omitempty"`                                 // 网卡信息
	Gpus           []*GpuInfo             `protobuf:"bytes,9,rep,name=gpus,proto3" json:"gpus,omitempty"`                                         // GPU信息
	Gateway        string                 `protobuf:"bytes,10,opt,name=gateway,proto3" json:"gateway,omitempty"`                                  // 默认网关
	Firewall       *FirewallInfo          `protobuf:"bytes,11,opt,name=firewall,proto3" json:"firewall,omitempty"`                                // 防火墙状态
	Swap           *SwapInfo              `protobuf:"bytes,12,opt,name=swap,proto3" json:"swap,omitempty"`                                        // Swap信息
	Timezone       string                 `protobuf:"bytes,13,opt,name=timezone,proto3" json:"timezone,omitempty"`                                // 时区
	SystemTime     string                 `protobuf:"bytes,14,opt,name=system_time,json=systemTime,proto3" json:"system_time,omitempty"`          // 系统时间
	HardwareTime   string                 `protobuf:"bytes,15,opt,name=hardware_time,json=hardwareTime,proto3" json:"hardware_time,omitempty"`    // 硬件时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemEnvInfo) Reset() {
	*x = SystemEnvInfo{}
	mi := &file_proto_server_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemEnvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEnvInfo) ProtoMessage() {}

func (x *SystemEnvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEnvInfo.ProtoReflect.Descriptor instead.
func (*SystemEnvInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{1}
}

func (x *SystemEnvInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemEnvInfo) GetVirtualization() string {
	if x != nil {
		return x.Virtualization
	}
	return ""
}

func (x *SystemEnvInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemEnvInfo) GetOs() *SystemInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *SystemEnvInfo) GetCpu() *CpuInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemEnvInfo) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemEnvInfo) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SystemEnvInfo) GetNetworks() []*NetworkInfo {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *SystemEnvInfo) GetGpus() []*GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *SystemEnvInfo) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *SystemEnvInfo) GetFirewall() *FirewallInfo {
	if x != nil {
		return x.Firewall
	}
	return nil
}

func (x *SystemEnvInfo) GetSwap() *SwapInfo {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *SystemEnvInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *SystemEnvInfo) GetSystemTime() string {
	if x != nil {
		return x.SystemTime
	}
	return ""
}

func (x *SystemEnvInfo) GetHardwareTime() string {
	if x != nil {
		return x.HardwareTime
	}
	return ""
}

// SystemInfo 操作系统信息
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 系统名称
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // 系统版本
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`   // 内核版本
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`       // 架构
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_server_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{2}
}

func (x *SystemInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// CpuInfo CPU信息
type CpuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`  // CPU型号
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"` // CPU核心数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuInfo) Reset() {
	*x = CpuInfo{}
	mi := &file_proto_server_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuInfo) ProtoMessage() {}

func (x *CpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuInfo.ProtoReflect.Descriptor instead.
func (*CpuInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{3}
}

func (x *CpuInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CpuInfo) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

// MemoryInfo 内存信息
type MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalKb       int64                  `protobuf:"varint,1,opt,name=total_kb,json=totalKb,proto3" json:"total_kb,omitempty"` // 总容量（kB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_proto_server_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryInfo) GetTotalKb() int64 {
	if x != nil {
		return x.TotalKb
	}
	return 0
}

// DiskInfo 磁盘信息
type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`                   // 设备名
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                       // 设备类型（ssd/hdd/nvme）
	TotalGb       int64                  `protobuf:"varint,3,opt,name=total_gb,json=totalGb,proto3" json:"total_gb,omitempty"` // 总容量（GB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_proto_server_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{5}
}

func (x *DiskInfo) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiskInfo) GetTotalGb() int64 {
	if x != nil {
		return x.TotalGb
	}
	return 0
}

// NetworkInfo 网卡信息
type NetworkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // 网卡名
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`         // IP地址
	Mac           string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`       // MAC地址
	Speed         int64                  `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`  // 网卡速率（Mbps）
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // 状态（up/down）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_proto_server_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkInfo) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *NetworkInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GpuInfo GPU信息
type GpuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // GPU名称
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                                     // 数量
	DriverVersion string                 `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"` // 驱动版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_proto_server_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{7}
}

func (x *GpuInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GpuInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GpuInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

// FirewallInfo 防火墙状态
type FirewallInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // 状态（active/inactive）
	Enabled       string                 `protobuf:"bytes,2,opt,name=enabled,proto3" json:"enabled,omitempty"` // 是否开机启动
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallInfo) Reset() {
	*x = FirewallInfo{}
	mi := &file_proto_server_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallInfo) ProtoMessage() {}

func (x *FirewallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallInfo.ProtoReflect.Descriptor instead.
func (*FirewallInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{8}
}

func (x *FirewallInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FirewallInfo) GetEnabled() string {
	if x != nil {
		return x.Enabled
	}
	return ""
}

// SwapInfo Swap信息
type SwapInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalKb       int64                  `protobuf:"varint,1,opt,name=total_kb,json=totalKb,proto3" json:"total_kb,omitempty"` // 总容量（kB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapInfo) Reset() {
	*x = SwapInfo{}
	mi := &file_proto_server_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapInfo) ProtoMessage() {}

func (x *SwapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapInfo.ProtoReflect.Descriptor instead.
func (*SwapInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{9}
}

func (x *SwapInfo) GetTotalKb() int64 {
	if x != nil {
		return x.TotalKb
	}
	return 0
}

// RegisterResponse 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 结果描述（失败时说明原因）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_server_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                                             // Agent IP
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                                        // Agent端口
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // 运行时间（秒）
	SystemTime    string                 `protobuf:"bytes,4,opt,name=system_time,json=systemTime,proto3" json:"system_time,omitempty"`           // 系统时间
	HardwareTime  string                 `protobuf:"bytes,5,opt,name=hardware_time,json=hardwareTime,proto3" json:"hardware_time,omitempty"`     // 硬件时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_server_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HeartbeatRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HeartbeatRequest) GetSystemTime() string {
	if x != nil {
		return x.SystemTime
	}
	return ""
}

func (x *HeartbeatRequest) GetHardwareTime() string {
	if x != nil {
		return x.HardwareTime
	}
	return ""
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AgentExit     bool                   `protobuf:"varint,2,opt,name=agent_exit,json=agentExit,proto3" json:"agent_exit,omitempty"` // 通知Agent退出（删除机器时使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_server_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetAgentExit() bool {
	if x != nil {
		return x.AgentExit
	}
	return false
}

// CopyFileRequest 文件传输请求（Agent发起）
type CopyFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"` // 源文件路径（Server端）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileRequest) Reset() {
	*x = CopyFileRequest{}
	mi := &file_proto_server_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileRequest) ProtoMessage() {}

func (x *CopyFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileRequest.ProtoReflect.Descriptor instead.
func (*CopyFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{13}
}

func (x *CopyFileRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

// FileChunk 文件块（Server流式返回）
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 块数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_server_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{14}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ListDirectoryRequest 目录列表请求
type ListDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`            // 目录路径
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"` // 是否递归
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryRequest) Reset() {
	*x = ListDirectoryRequest{}
	mi := &file_proto_server_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryRequest) ProtoMessage() {}

func (x *ListDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{15}
}

func (x *ListDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirectoryRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// FileInfo 文件信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                      // 相对路径
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`                      // 是否是目录
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                                     // 文件大小（字节）
	ModifiedTime  int64                  `protobuf:"varint,4,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"` // 修改时间（Unix时间戳）
	Permissions   string                 `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`                        // 权限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_server_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{16}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModifiedTime() int64 {
	if x != nil {
		return x.ModifiedTime
	}
	return 0
}

func (x *FileInfo) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

// ListDirectoryResponse 目录列表响应
type ListDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"` // 文件列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResponse) Reset() {
	*x = ListDirectoryResponse{}
	mi := &file_proto_server_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResponse) ProtoMessage() {}

func (x *ListDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_server_proto_rawDescGZIP(), []int{17}
}

func (x *ListDirectoryResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_proto_server_server_proto protoreflect.FileDescriptor

const file_proto_server_server_proto_rawDesc = "" +
	"\n" +
	"\x19proto/server/server.proto\x12\x06server\"}\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x120\n" +
	"\benv_info\x18\x04 \x01(\v2\x15.server.SystemEnvInfoR\aenvInfo\"\xbf\x04\n" +
	"\rSystemEnvInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12&\n" +
	"\x0evirtualization\x18\x02 \x01(\tR\x0evirtualization\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\"\n" +
	"\x02os\x18\x04 \x01(\v2\x12.server.SystemInfoR\x02os\x12!\n" +
	"\x03cpu\x18\x05 \x01(\v2\x0f.server.CpuInfoR\x03cpu\x12*\n" +
	"\x06memory\x18\x06 \x01(\v2\x12.server.MemoryInfoR\x06memory\x12&\n" +
	"\x05disks\x18\a \x03(\v2\x10.server.DiskInfoR\x05disks\x12/\n" +
	"\bnetworks\x18\b \x03(\v2\x13.server.NetworkInfoR\bnetworks\x12#\n" +
	"\x04gpus\x18\t \x03(\v2\x0f.server.GpuInfoR\x04gpus\x12\x18\n" +
	"\agateway\x18\n" +
	" \x01(\tR\agateway\x120\n" +
	"\bfirewall\x18\v \x01(\v2\x14.server.FirewallInfoR\bfirewall\x12$\n" +
	"\x04swap\x18\f \x01(\v2\x10.server.SwapInfoR\x04swap\x12\x1a\n" +
	"\btimezone\x18\r \x01(\tR\btimezone\x12\x1f\n" +
	"\vsystem_time\x18\x0e \x01(\tR\n" +
	"systemTime\x12#\n" +
	"\rhardware_time\x18\x0f \x01(\tR\fhardwareTime\"f\n" +
	"\n" +
	"SystemInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\"5\n" +
	"\aCpuInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\"'\n" +
	"\n" +
	"MemoryInfo\x12\x19\n" +
	"\btotal_kb\x18\x01 \x01(\x03R\atotalKb\"Q\n" +
	"\bDiskInfo\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\btotal_gb\x18\x03 \x01(\x03R\atotalGb\"q\n" +
	"\vNetworkInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x03R\x05speed\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"Z\n" +
	"\aGpuInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\"@\n" +
	"\fFirewallInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\tR\aenabled\"%\n" +
	"\bSwapInfo\x12\x19\n" +
	"\btotal_kb\x18\x01 \x01(\x03R\atotalKb\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa3\x01\n" +
	"\x10HeartbeatRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vsystem_time\x18\x04 \x01(\tR\n" +
	"systemTime\x12#\n" +
	"\rhardware_time\x18\x05 \x01(\tR\fhardwareTime\"L\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"agent_exit\x18\x02 \x01(\bR\tagentExit\"2\n" +
	"\x0fCopyFileRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"H\n" +
	"\x14ListDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\x90\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12#\n" +
	"\rmodified_time\x18\x04 \x01(\x03R\fmodifiedTime\x12 \n" +
	"\vpermissions\x18\x05 \x01(\tR\vpermissions\"?\n" +
	"\x15ListDirectoryResponse\x12&\n" +
	"\x05files\x18\x01 \x03(\v2\x10.server.FileInfoR\x05files2\x98\x02\n" +
	"\rServerService\x12=\n" +
	"\bRegister\x12\x17.server.RegisterRequest\x1a\x18.server.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.server.HeartbeatRequest\x1a\x19.server.HeartbeatResponse\x128\n" +
	"\bCopyFile\x12\x17.server.CopyFileRequest\x1a\x11.server.FileChunk0\x01\x12L\n" +
	"\rListDirectory\x12\x1c.server.ListDirectoryRequest\x1a\x1d.server.ListDirectoryResponseB#Z!fastdp-orbit/backend/proto/serverb\x06proto3"

var (
	file_proto_server_server_proto_rawDescOnce sync.Once
	file_proto_server_server_proto_rawDescData []byte
)

func file_proto_server_server_proto_rawDescGZIP() []byte {
	file_proto_server_server_proto_rawDescOnce.Do(func() {
		file_proto_server_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_server_proto_rawDesc), len(file_proto_server_server_proto_rawDesc)))
	})
	return file_proto_server_server_proto_rawDescData
}

var file_proto_server_server_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_server_server_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: server.RegisterRequest
	(*SystemEnvInfo)(nil),         // 1: server.SystemEnvInfo
	(*SystemInfo)(nil),            // 2: server.SystemInfo
	(*CpuInfo)(nil),               // 3: server.CpuInfo
	(*MemoryInfo)(nil),            // 4: server.MemoryInfo
	(*DiskInfo)(nil),              // 5: server.DiskInfo
	(*NetworkInfo)(nil),           // 6: server.NetworkInfo
	(*GpuInfo)(nil),               // 7: server.GpuInfo
	(*FirewallInfo)(nil),          // 8: server.FirewallInfo
	(*SwapInfo)(nil),              // 9: server.SwapInfo
	(*RegisterResponse)(nil),      // 10: server.RegisterResponse
	(*HeartbeatRequest)(nil),      // 11: server.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 12: server.HeartbeatResponse
	(*CopyFileRequest)(nil),       // 13: server.CopyFileRequest
	(*FileChunk)(nil),             // 14: server.FileChunk
	(*ListDirectoryRequest)(nil),  // 15: server.ListDirectoryRequest
	(*FileInfo)(nil),              // 16: server.FileInfo
	(*ListDirectoryResponse)(nil), // 17: server.ListDirectoryResponse
}
var file_proto_server_server_proto_depIdxs = []int32{
	1,  // 0: server.RegisterRequest.env_info:type_name -> server.SystemEnvInfo
	2,  // 1: server.SystemEnvInfo.os:type_name -> server.SystemInfo
	3,  // 2: server.SystemEnvInfo.cpu:type_name -> server.CpuInfo
	4,  // 3: server.SystemEnvInfo.memory:type_name -> server.MemoryInfo
	5,  // 4: server.SystemEnvInfo.disks:type_name -> server.DiskInfo
	6,  // 5: server.SystemEnvInfo.networks:type_name -> server.NetworkInfo
	7,  // 6: server.SystemEnvInfo.gpus:type_name -> server.GpuInfo
	8,  // 7: server.SystemEnvInfo.firewall:type_name -> server.FirewallInfo
	9,  // 8: server.SystemEnvInfo.swap:type_name -> server.SwapInfo
	16, // 9: server.ListDirectoryResponse.files:type_name -> server.FileInfo
	0,  // 10: server.ServerService.Register:input_type -> server.RegisterRequest
	11, // 11: server.ServerService.Heartbeat:input_type -> server.HeartbeatRequest
	13, // 12: server.ServerService.CopyFile:input_type -> server.CopyFileRequest
	15, // 13: server.ServerService.ListDirectory:input_type -> server.ListDirectoryRequest
	10, // 14: server.ServerService.Register:output_type -> server.RegisterResponse
	12, // 15: server.ServerService.Heartbeat:output_type -> server.HeartbeatResponse
	14, // 16: server.ServerService.CopyFile:output_type -> server.FileChunk
	17, // 17: server.ServerService.ListDirectory:output_type -> server.ListDirectoryResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_server_server_proto_init() }
func file_proto_server_server_proto_init() {
	if File_proto_server_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_server_proto_rawDesc), len(file_proto_server_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_server_proto_goTypes,
		DependencyIndexes: file_proto_server_server_proto_depIdxs,
		MessageInfos:      file_proto_server_server_proto_msgTypes,
	}.Build()
	File_proto_server_server_proto = out.File
	file_proto_server_server_proto_goTypes = nil
	file_proto_server_server_proto_depIdxs = nil
}
