// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecRequest 单个执行请求（对应Playbook中的一个task）
type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`                                                            // 目标机器ID（对应Ansible的inventory主机）
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`                                                                                   // 模块名（如"shell"、"copy"、"file"、"service"）
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 模块参数
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                                     // 任务唯一ID（批量执行时用于关联响应）
	Timeout       int32                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                                // 超时时间（秒），0表示不超时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ExecRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ExecRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// BatchExecRequest 批量执行请求（对应Playbook的一次运行）
type BatchExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"` // 批次ID（标识整个Playbook的执行）
	Tasks         []*ExecRequest         `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`                    // 批量任务列表
	Ordered       bool                   `protobuf:"varint,3,opt,name=ordered,proto3" json:"ordered,omitempty"`               // 是否按顺序执行（false表示并发执行）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExecRequest) Reset() {
	*x = BatchExecRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecRequest) ProtoMessage() {}

func (x *BatchExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecRequest.ProtoReflect.Descriptor instead.
func (*BatchExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *BatchExecRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchExecRequest) GetTasks() []*ExecRequest {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *BatchExecRequest) GetOrdered() bool {
	if x != nil {
		return x.Ordered
	}
	return false
}

// ExecResponse 执行响应
type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`     // 目标机器ID（回显，便于关联）
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`              // 任务ID（回显，批量执行时关联请求）
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                         // 执行是否成功（不代表是否有变更）
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`                            // 标准输出（模块正常输出）
	Changed       bool                   `protobuf:"varint,5,opt,name=changed,proto3" json:"changed,omitempty"`                         // 是否产生变更（幂等性核心：true=有变更，false=无变更）
	Error         *ErrorDetail           `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                              // 错误详情（success=false时非空）
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // 执行耗时（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ExecResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ExecResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ErrorDetail 错误详情
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 错误码（1001=模块不存在，1002=参数错误，1003=执行超时）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误描述
	Trace         string                 `protobuf:"bytes,3,opt,name=trace,proto3" json:"trace,omitempty"`     // 错误堆栈（调试用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

// SystemInfoRequest 系统信息请求
type SystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // 目标机器ID
	InfoTypes     []string               `protobuf:"bytes,2,rep,name=info_types,json=infoTypes,proto3" json:"info_types,omitempty"` // 筛选信息类型（为空返回所有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoRequest) Reset() {
	*x = SystemInfoRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRequest) ProtoMessage() {}

func (x *SystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SystemInfoRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *SystemInfoRequest) GetInfoTypes() []string {
	if x != nil {
		return x.InfoTypes
	}
	return nil
}

// SystemInfoResponse 系统信息响应
type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // 目标机器ID（回显）
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                      // 结果描述（失败时说明原因）
	EnvInfo       *SystemEnvInfo         `protobuf:"bytes,4,opt,name=env_info,json=envInfo,proto3" json:"env_info,omitempty"`       // 机器环境信息（success为true时有效）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SystemInfoResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *SystemInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SystemInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SystemInfoResponse) GetEnvInfo() *SystemEnvInfo {
	if x != nil {
		return x.EnvInfo
	}
	return nil
}

// SystemEnvInfo 机器环境信息详情
type SystemEnvInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                                 // 主机名
	Virtualization string                 `protobuf:"bytes,2,opt,name=virtualization,proto3" json:"virtualization,omitempty"`                     // 虚拟化类型（none/kvm/vmware/docker等）
	UptimeSeconds  int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // 运行时间（秒）
	Os             *SystemInfo            `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                             // 操作系统信息
	Cpu            *CpuInfo               `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`                                           // CPU信息
	Memory         *MemoryInfo            `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`                                     // 内存信息
	Disks          []*DiskInfo            `protobuf:"bytes,7,rep,name=disks,proto3" json:"disks,omitempty"`                                       // 磁盘信息（可能多块磁盘）
	Networks       []*NetworkInfo         `protobuf:"bytes,8,rep,name=networks,proto3" json:"networks,omitempty"`                                 // 网卡信息
	Gpus           []*GpuInfo             `protobuf:"bytes,9,rep,name=gpus,proto3" json:"gpus,omitempty"`                                         // GPU信息
	Gateway        string                 `protobuf:"bytes,10,opt,name=gateway,proto3" json:"gateway,omitempty"`                                  // 默认网关
	Firewall       *FirewallInfo          `protobuf:"bytes,11,opt,name=firewall,proto3" json:"firewall,omitempty"`                                // 防火墙状态
	Swap           *SwapInfo              `protobuf:"bytes,12,opt,name=swap,proto3" json:"swap,omitempty"`                                        // Swap信息
	Timezone       string                 `protobuf:"bytes,13,opt,name=timezone,proto3" json:"timezone,omitempty"`                                // 时区（如"Asia/Shanghai"）
	SystemTime     string                 `protobuf:"bytes,14,opt,name=system_time,json=systemTime,proto3" json:"system_time,omitempty"`          // 系统时间
	HardwareTime   string                 `protobuf:"bytes,15,opt,name=hardware_time,json=hardwareTime,proto3" json:"hardware_time,omitempty"`    // 硬件时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemEnvInfo) Reset() {
	*x = SystemEnvInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemEnvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEnvInfo) ProtoMessage() {}

func (x *SystemEnvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEnvInfo.ProtoReflect.Descriptor instead.
func (*SystemEnvInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SystemEnvInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemEnvInfo) GetVirtualization() string {
	if x != nil {
		return x.Virtualization
	}
	return ""
}

func (x *SystemEnvInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemEnvInfo) GetOs() *SystemInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *SystemEnvInfo) GetCpu() *CpuInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemEnvInfo) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemEnvInfo) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SystemEnvInfo) GetNetworks() []*NetworkInfo {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *SystemEnvInfo) GetGpus() []*GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *SystemEnvInfo) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *SystemEnvInfo) GetFirewall() *FirewallInfo {
	if x != nil {
		return x.Firewall
	}
	return nil
}

func (x *SystemEnvInfo) GetSwap() *SwapInfo {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *SystemEnvInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *SystemEnvInfo) GetSystemTime() string {
	if x != nil {
		return x.SystemTime
	}
	return ""
}

func (x *SystemEnvInfo) GetHardwareTime() string {
	if x != nil {
		return x.HardwareTime
	}
	return ""
}

// SystemInfo 操作系统信息
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 系统名称（如"Kylin Linux Advanced Server V10"）
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // 系统版本（如"Halberd"）
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`   // 内核版本（如"4.19.90-89.11.v2401.ky10.x86_64"）
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`       // 架构（如"x86_64"）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SystemInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// CpuInfo CPU信息
type CpuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`  // CPU型号（如"Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz"）
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"` // CPU核心数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuInfo) Reset() {
	*x = CpuInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuInfo) ProtoMessage() {}

func (x *CpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuInfo.ProtoReflect.Descriptor instead.
func (*CpuInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CpuInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CpuInfo) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

// MemoryInfo 内存信息
type MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalKb       int64                  `protobuf:"varint,1,opt,name=total_kb,json=totalKb,proto3" json:"total_kb,omitempty"` // 总容量（kB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryInfo) GetTotalKb() int64 {
	if x != nil {
		return x.TotalKb
	}
	return 0
}

// DiskInfo 磁盘信息
type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`                   // 设备名（如"/dev/sda"）
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                       // 设备类型（ssd/hdd/nvme）
	TotalGb       int64                  `protobuf:"varint,3,opt,name=total_gb,json=totalGb,proto3" json:"total_gb,omitempty"` // 总容量（GB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DiskInfo) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiskInfo) GetTotalGb() int64 {
	if x != nil {
		return x.TotalGb
	}
	return 0
}

// NetworkInfo 网卡信息
type NetworkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // 网卡名（如"eth0"）
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`         // IP地址（如"10.243.240.1/24"，DOWN时为空）
	Mac           string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`       // MAC地址
	Speed         int64                  `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`  // 网卡速率（Mbps，DOWN时为0）
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // 状态（up/down）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkInfo) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *NetworkInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GpuInfo GPU信息
type GpuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // GPU名称（如"NVIDIA A100-SXM4-40GB"）
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                                     // 数量
	DriverVersion string                 `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"` // 驱动版本（如"535.129.03"，未安装驱动时为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *GpuInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GpuInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GpuInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

// FirewallInfo 防火墙状态
type FirewallInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // 状态（active/inactive）
	Enabled       string                 `protobuf:"bytes,2,opt,name=enabled,proto3" json:"enabled,omitempty"` // 是否开机启动（enabled/disabled）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallInfo) Reset() {
	*x = FirewallInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallInfo) ProtoMessage() {}

func (x *FirewallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallInfo.ProtoReflect.Descriptor instead.
func (*FirewallInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *FirewallInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FirewallInfo) GetEnabled() string {
	if x != nil {
		return x.Enabled
	}
	return ""
}

// SwapInfo Swap信息
type SwapInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalKb       int64                  `protobuf:"varint,1,opt,name=total_kb,json=totalKb,proto3" json:"total_kb,omitempty"` // 总容量（kB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapInfo) Reset() {
	*x = SwapInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapInfo) ProtoMessage() {}

func (x *SwapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapInfo.ProtoReflect.Descriptor instead.
func (*SwapInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *SwapInfo) GetTotalKb() int64 {
	if x != nil {
		return x.TotalKb
	}
	return 0
}

var File_proto_agent_agent_proto protoreflect.FileDescriptor

const file_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent/agent.proto\x12\x05agent\"\xfa\x01\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12B\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2\".agent.ExecRequest.ParametersEntryR\n" +
	"parameters\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x10BatchExecRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12(\n" +
	"\x05tasks\x18\x02 \x03(\v2\x12.agent.ExecRequestR\x05tasks\x12\x18\n" +
	"\aordered\x18\x03 \x01(\bR\aordered\"\xdd\x01\n" +
	"\fExecResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x18\n" +
	"\achanged\x18\x05 \x01(\bR\achanged\x12(\n" +
	"\x05error\x18\x06 \x01(\v2\x12.agent.ErrorDetailR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\"Q\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05trace\x18\x03 \x01(\tR\x05trace\"Q\n" +
	"\x11SystemInfoRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1d\n" +
	"\n" +
	"info_types\x18\x02 \x03(\tR\tinfoTypes\"\x98\x01\n" +
	"\x12SystemInfoResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12/\n" +
	"\benv_info\x18\x04 \x01(\v2\x14.agent.SystemEnvInfoR\aenvInfo\"\xb7\x04\n" +
	"\rSystemEnvInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12&\n" +
	"\x0evirtualization\x18\x02 \x01(\tR\x0evirtualization\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\x02os\x18\x04 \x01(\v2\x11.agent.SystemInfoR\x02os\x12 \n" +
	"\x03cpu\x18\x05 \x01(\v2\x0e.agent.CpuInfoR\x03cpu\x12)\n" +
	"\x06memory\x18\x06 \x01(\v2\x11.agent.MemoryInfoR\x06memory\x12%\n" +
	"\x05disks\x18\a \x03(\v2\x0f.agent.DiskInfoR\x05disks\x12.\n" +
	"\bnetworks\x18\b \x03(\v2\x12.agent.NetworkInfoR\bnetworks\x12\"\n" +
	"\x04gpus\x18\t \x03(\v2\x0e.agent.GpuInfoR\x04gpus\x12\x18\n" +
	"\agateway\x18\n" +
	" \x01(\tR\agateway\x12/\n" +
	"\bfirewall\x18\v \x01(\v2\x13.agent.FirewallInfoR\bfirewall\x12#\n" +
	"\x04swap\x18\f \x01(\v2\x0f.agent.SwapInfoR\x04swap\x12\x1a\n" +
	"\btimezone\x18\r \x01(\tR\btimezone\x12\x1f\n" +
	"\vsystem_time\x18\x0e \x01(\tR\n" +
	"systemTime\x12#\n" +
	"\rhardware_time\x18\x0f \x01(\tR\fhardwareTime\"f\n" +
	"\n" +
	"SystemInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\"5\n" +
	"\aCpuInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\"'\n" +
	"\n" +
	"MemoryInfo\x12\x19\n" +
	"\btotal_kb\x18\x01 \x01(\x03R\atotalKb\"Q\n" +
	"\bDiskInfo\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\btotal_gb\x18\x03 \x01(\x03R\atotalGb\"q\n" +
	"\vNetworkInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x03R\x05speed\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"Z\n" +
	"\aGpuInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\"@\n" +
	"\fFirewallInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\tR\aenabled\"%\n" +
	"\bSwapInfo\x12\x19\n" +
	"\btotal_kb\x18\x01 \x01(\x03R\atotalKb2\xc2\x01\n" +
	"\fAgentService\x12/\n" +
	"\x04Exec\x12\x12.agent.ExecRequest\x1a\x13.agent.ExecResponse\x12;\n" +
	"\tBatchExec\x12\x17.agent.BatchExecRequest\x1a\x13.agent.ExecResponse0\x01\x12D\n" +
	"\rGetSystemInfo\x12\x18.agent.SystemInfoRequest\x1a\x19.agent.SystemInfoResponseB\"Z fastdp-orbit/backend/proto/agentb\x06proto3"

var (
	file_proto_agent_agent_proto_rawDescOnce sync.Once
	file_proto_agent_agent_proto_rawDescData []byte
)

func file_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)))
	})
	return file_proto_agent_agent_proto_rawDescData
}

var file_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_agent_agent_proto_goTypes = []any{
	(*ExecRequest)(nil),        // 0: agent.ExecRequest
	(*BatchExecRequest)(nil),   // 1: agent.BatchExecRequest
	(*ExecResponse)(nil),       // 2: agent.ExecResponse
	(*ErrorDetail)(nil),        // 3: agent.ErrorDetail
	(*SystemInfoRequest)(nil),  // 4: agent.SystemInfoRequest
	(*SystemInfoResponse)(nil), // 5: agent.SystemInfoResponse
	(*SystemEnvInfo)(nil),      // 6: agent.SystemEnvInfo
	(*SystemInfo)(nil),         // 7: agent.SystemInfo
	(*CpuInfo)(nil),            // 8: agent.CpuInfo
	(*MemoryInfo)(nil),         // 9: agent.MemoryInfo
	(*DiskInfo)(nil),           // 10: agent.DiskInfo
	(*NetworkInfo)(nil),        // 11: agent.NetworkInfo
	(*GpuInfo)(nil),            // 12: agent.GpuInfo
	(*FirewallInfo)(nil),       // 13: agent.FirewallInfo
	(*SwapInfo)(nil),           // 14: agent.SwapInfo
	nil,                        // 15: agent.ExecRequest.ParametersEntry
}
var file_proto_agent_agent_proto_depIdxs = []int32{
	15, // 0: agent.ExecRequest.parameters:type_name -> agent.ExecRequest.ParametersEntry
	0,  // 1: agent.BatchExecRequest.tasks:type_name -> agent.ExecRequest
	3,  // 2: agent.ExecResponse.error:type_name -> agent.ErrorDetail
	6,  // 3: agent.SystemInfoResponse.env_info:type_name -> agent.SystemEnvInfo
	7,  // 4: agent.SystemEnvInfo.os:type_name -> agent.SystemInfo
	8,  // 5: agent.SystemEnvInfo.cpu:type_name -> agent.CpuInfo
	9,  // 6: agent.SystemEnvInfo.memory:type_name -> agent.MemoryInfo
	10, // 7: agent.SystemEnvInfo.disks:type_name -> agent.DiskInfo
	11, // 8: agent.SystemEnvInfo.networks:type_name -> agent.NetworkInfo
	12, // 9: agent.SystemEnvInfo.gpus:type_name -> agent.GpuInfo
	13, // 10: agent.SystemEnvInfo.firewall:type_name -> agent.FirewallInfo
	14, // 11: agent.SystemEnvInfo.swap:type_name -> agent.SwapInfo
	0,  // 12: agent.AgentService.Exec:input_type -> agent.ExecRequest
	1,  // 13: agent.AgentService.BatchExec:input_type -> agent.BatchExecRequest
	4,  // 14: agent.AgentService.GetSystemInfo:input_type -> agent.SystemInfoRequest
	2,  // 15: agent.AgentService.Exec:output_type -> agent.ExecResponse
	2,  // 16: agent.AgentService.BatchExec:output_type -> agent.ExecResponse
	5,  // 17: agent.AgentService.GetSystemInfo:output_type -> agent.SystemInfoResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_agent_agent_proto_init() }
func file_proto_agent_agent_proto_init() {
	if File_proto_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_agent_proto = out.File
	file_proto_agent_agent_proto_goTypes = nil
	file_proto_agent_agent_proto_depIdxs = nil
}
